version: "3.9"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: postgres
  session:
    store-type: none

  data:
    redis:
      host: localhost
      port: 6379
      # password: your_password   # если включите пароль в redis
      timeout: 2s
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: price.change:com.dto.PriceChangeEvent
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: price.change:com.dto.PriceChangeEvent
      group-id: processing-service
      auto-offset-reset: earliest

jwt:
  secret: "very-secret-key-change-me-1234567890"
  expiration-ms: 3600000

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    ports:
      - "5432:5432"

